@baseUrl = http://localhost:3333

POST {{baseUrl}}/restaurants
content-type: application/json

{
    "name": "John Doe",
	"email": "johndoe@email.com",
	"phone": "+55 98 99999-9999",
	"restaurantName": "pizza shop"
}

###

POST {{baseUrl}}/authenticate
content-type: application/json

{
	"email": "admin@admin.com"
}

###